name = "atharvkotekar"
compatibility_date = "2024-03-24"

[site]
bucket = "./dist"

[build]
command = "npm run build"
watch_dir = "src"

[[rules]]
type = "NavigationRoute"
route = "/*"
handler = "index.html" 